export default [
    {
      "_id": "quiz-104-a",
      "courseId": "RS104",
      "title": "Intro to Organic Reactions",
      "description": "Covers the basics of reaction types and mechanisms.",
      "quizType": "Graded Quiz",
      "assignmentGroup": "Quizzes",
      "shuffleAnswers": true,
      "timeLimit": 30,
      "multipleAttempts": true,
      "maxAttempts": 3,
      "showCorrectAnswers": true,
      "accessCode": "",
      "oneQuestionAtATime": true,
      "webcamRequired": false,
      "lockQuestionsAfterAnswering": false,
      "dueDate": "2024-04-30T23:59:00.000Z",
      "availableFrom": "2024-04-01T00:00:00.000Z",
      "availableUntil": "2024-05-01T00:00:00.000Z",
      "published": true,
      "totalPoints": 5,
      "questions": ["q-104-1", "q-104-2"]
    },
    {
      "_id": "quiz-107-a",
      "courseId": "RS107",
      "title": "Elvish Vocabulary Quiz",
      "description": "Test your knowledge of basic Elvish terms and scripts.",
      "quizType": "Practice Quiz",
      "assignmentGroup": "Quizzes",
      "shuffleAnswers": false,
      "timeLimit": 15,
      "multipleAttempts": false,
      "maxAttempts": 1,
      "showCorrectAnswers": true,
      "accessCode": "eldar",
      "oneQuestionAtATime": false,
      "webcamRequired": false,
      "lockQuestionsAfterAnswering": false,
      "dueDate": "2024-04-30T23:59:00.000Z",
      "availableFrom": "2024-04-05T00:00:00.000Z",
      "availableUntil": "2024-05-05T00:00:00.000Z",
      "published": true,
      "totalPoints": 6,
      "questions": ["q-107-1", "q-107-2", "q-107-3"]
    },
    {
      "_id": "quiz-108-a",
      "courseId": "RS108",
      "title": "Diplomatic Treaties of Middle-earth",
      "description": "Analyze the inter-species diplomacy between Men, Elves, and Dwarves.",
      "quizType": "Graded Quiz",
      "assignmentGroup": "Exams",
      "shuffleAnswers": true,
      "timeLimit": 20,
      "multipleAttempts": false,
      "maxAttempts": 1,
      "showCorrectAnswers": false,
      "accessCode": "",
      "oneQuestionAtATime": true,
      "webcamRequired": false,
      "lockQuestionsAfterAnswering": true,
      "dueDate": "2024-04-30T23:59:00.000Z",
      "availableFrom": "2024-04-10T00:00:00.000Z",
      "availableUntil": "2024-05-10T00:00:00.000Z",
      "published": true,
      "totalPoints": 4,
      "questions": ["q-108-1", "q-108-2"]
    }
  ]
